package models

import (
	"time"

	"github.com/google/uuid"
)

// Customer represents a business customer account
type Customer struct {
	ID           uuid.UUID              `json:"id" db:"id"`
	BAN          string                 `json:"ban" db:"ban"`
	CompanyName  string                 `json:"company_name" db:"company_name"`
	LegalName    *string                `json:"legal_name,omitempty" db:"legal_name"`
	Status       string                 `json:"status" db:"status"`
	CustomerType string                 `json:"customer_type" db:"customer_type"`
	
	// JSONB fields
	Contact      map[string]interface{} `json:"contact" db:"contact"`
	Address      map[string]interface{} `json:"address" db:"address"`
	Services     map[string]interface{} `json:"services" db:"services"`
	KYCData      map[string]interface{} `json:"kyc_data,omitempty" db:"kyc_data"`
	BusinessInfo map[string]interface{} `json:"business_info,omitempty" db:"business_info"`
	ExternalIDs  map[string]interface{} `json:"external_ids,omitempty" db:"external_ids"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty" db:"custom_fields"`
	
	// Financial
	CreditLimit     *float64 `json:"credit_limit,omitempty" db:"credit_limit"`
	CurrentBalance  float64  `json:"current_balance" db:"current_balance"`
	PrepaidBalance  float64  `json:"prepaid_balance" db:"prepaid_balance"`
	PaymentTerms    int      `json:"payment_terms" db:"payment_terms"`
	BillingCycle    string   `json:"billing_cycle" db:"billing_cycle"`
	Currency        string   `json:"currency" db:"currency"`
	
	// Audit
	CreatedAt time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt time.Time  `json:"updated_at" db:"updated_at"`
	CreatedBy *string    `json:"created_by,omitempty" db:"created_by"`
	UpdatedBy *string    `json:"updated_by,omitempty" db:"updated_by"`
}

// CreateCustomerRequest for creating new customers
// Note: BAN is auto-generated by the backend and not included in the request
type CreateCustomerRequest struct {
	CompanyName  string                  `json:"company_name" binding:"required"`
	LegalName    string                  `json:"legal_name"`
	CustomerType string                  `json:"customer_type" binding:"required,oneof=PREPAID POSTPAID RESELLER"`
	
	Contact      map[string]interface{}  `json:"contact" binding:"required"`
	Address      map[string]interface{}  `json:"address" binding:"required"`
	Services     map[string]interface{}  `json:"services"`
	KYCData      map[string]interface{}  `json:"kyc_data"`
	BusinessInfo map[string]interface{}  `json:"business_info"`
	ExternalIDs  map[string]interface{}  `json:"external_ids"`
	CustomFields map[string]interface{}  `json:"custom_fields"`
	
	CreditLimit    *float64 `json:"credit_limit"`
	PaymentTerms   int      `json:"payment_terms"`
	BillingCycle   string   `json:"billing_cycle"`
}

// UpdateCustomerRequest for updating customers
type UpdateCustomerRequest struct {
	CompanyName  *string                 `json:"company_name"`
	LegalName    *string                 `json:"legal_name"`
	Status       *string                 `json:"status" binding:"omitempty,oneof=ACTIVE SUSPENDED TRIAL CLOSED"`
	
	Contact      map[string]interface{}  `json:"contact"`
	Address      map[string]interface{}  `json:"address"`
	Services     map[string]interface{}  `json:"services"`
	KYCData      map[string]interface{}  `json:"kyc_data"`
	BusinessInfo map[string]interface{}  `json:"business_info"`
	ExternalIDs  map[string]interface{}  `json:"external_ids"`
	CustomFields map[string]interface{}  `json:"custom_fields"`
	
	CreditLimit    *float64 `json:"credit_limit"`
	PaymentTerms   *int     `json:"payment_terms"`
	BillingCycle   *string  `json:"billing_cycle"`
}

// CustomerListResponse for paginated customer lists
type CustomerListResponse struct {
	Customers  []Customer         `json:"customers"`
	Pagination PaginationResponse `json:"pagination"`
}

// PaginationResponse for list endpoints
type PaginationResponse struct {
	Page       int   `json:"page"`
	PerPage    int   `json:"per_page"`
	Total      int64 `json:"total"`
	TotalPages int   `json:"total_pages"`
}
