// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{}`

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}
