# Core Infrastructure Services
# These services are always running in development
version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: warp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - warp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Consul for service discovery
  consul:
    image: consul:1.16
    container_name: warp-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -datacenter=dc1
    volumes:
      - consul-data:/consul/data
    networks:
      - warp-network
    environment:
      CONSUL_BIND_INTERFACE: eth0

  # RabbitMQ for message queuing
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: warp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: warp
      RABBITMQ_DEFAULT_PASS: warp_dev
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - warp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cloud SQL Proxy for GCP database connection
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    container_name: warp-sql-proxy
    command: |
      /cloud_sql_proxy
      -instances=ringer-472421:us-central1:ringer-db=tcp:0.0.0.0:5432
      -credential_file=/config/service-account.json
    volumes:
      - ./config/service-account.json:/config/service-account.json:ro
    ports:
      - "5432:5432"
    networks:
      - warp-network

  # BigQuery Emulator for local development
  bigquery-emulator:
    image: ghcr.io/goccy/bigquery-emulator:latest
    container_name: warp-bigquery-emulator
    ports:
      - "9050:9050"
      - "9060:9060"
    command: |
      --project=ringer-472421
      --dataset=warp_telecom_dev
    volumes:
      - ./config/bigquery-schema.yaml:/config/schema.yaml:ro
    networks:
      - warp-network

  # Pub/Sub Emulator for local development
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    container_name: warp-pubsub-emulator
    ports:
      - "8085:8085"
    command: |
      gcloud beta emulators pubsub start
      --host-port=0.0.0.0:8085
      --project=ringer-472421
    environment:
      PUBSUB_PROJECT_ID: ringer-472421
    networks:
      - warp-network

volumes:
  redis-data:
  consul-data:
  rabbitmq-data:

networks:
  warp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16