import { useQuery, useMutation, useQueryClient, UseQueryOptions } from '@tanstack/react-query';
import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL;

// Types based on backend models
export interface Customer {
  id: string;
  ban: string;
  company_name: string;
  legal_name?: string;
  status: string;
  customer_type: string;
  contact: Record<string, any>;
  address: Record<string, any>;
  services: {
    voice?: {
      enabled: boolean;
      types: string[];
    };
    messaging?: {
      enabled: boolean;
      types: string[];
    };
    telecom_data?: {
      enabled: boolean;
      types: string[];
    };
  };
  kyc_data?: Record<string, any>;
  business_info?: Record<string, any>;
  external_ids?: Record<string, any>;
  custom_fields?: Record<string, any>;
  credit_limit?: number;
  current_balance: number;
  prepaid_balance: number;
  payment_terms: number;
  billing_cycle: string;
  currency: string;
  created_at: string;
  updated_at: string;
  created_by?: string;
  updated_by?: string;
}

export interface CreateCustomerRequest {
  // Note: BAN is auto-generated by backend
  company_name: string;
  legal_name?: string;
  customer_type: 'PREPAID' | 'POSTPAID' | 'RESELLER';
  contact: Record<string, any>;
  address: Record<string, any>;
  services?: Record<string, any>;
  kyc_data?: Record<string, any>;
  business_info?: Record<string, any>;
  external_ids?: Record<string, any>;
  custom_fields?: Record<string, any>;
  credit_limit?: number;
  payment_terms?: number;
  billing_cycle?: string;
}

export interface UpdateCustomerRequest {
  company_name?: string;
  legal_name?: string;
  status?: 'ACTIVE' | 'SUSPENDED' | 'TRIAL' | 'CLOSED';
  contact?: Record<string, any>;
  address?: Record<string, any>;
  services?: Record<string, any>;
  kyc_data?: Record<string, any>;
  business_info?: Record<string, any>;
  external_ids?: Record<string, any>;
  custom_fields?: Record<string, any>;
  credit_limit?: number;
  payment_terms?: number;
  billing_cycle?: string;
}

export interface CustomerListResponse {
  items: Customer[];
  pagination: {
    page: number;
    per_page: number;
    total: number;
    total_pages: number;
  };
}

interface APIResponse<T> {
  success: boolean;
  data: T;
  error?: {
    code: string;
    message: string;
  };
}

// Helper to get auth token from localStorage
const getAuthToken = () => {
  return localStorage.getItem('access_token');
};

// API client with auth
const api = axios.create({
  baseURL: API_URL,
});

api.interceptors.request.use((config) => {
  const token = getAuthToken();
  console.log('🔐 Axios interceptor - Token:', token ? `${token.substring(0, 20)}...` : 'NOT FOUND');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
    console.log('✅ Authorization header set');
  } else {
    console.error('❌ No token found in localStorage!');
  }
  return config;
});

// API Functions
const fetchCustomers = async (
  page = 1,
  perPage = 20,
  search?: string,
  status?: string
): Promise<CustomerListResponse> => {
  const params = new URLSearchParams();
  params.append('page', page.toString());
  params.append('per_page', perPage.toString());
  if (search) params.append('search', search);
  if (status) params.append('status', status);

  const response = await api.get<APIResponse<CustomerListResponse>>(
    `/v1/customers?${params.toString()}`
  );
  return response.data.data;
};

const fetchCustomer = async (id: string): Promise<Customer> => {
  const response = await api.get<APIResponse<Customer>>(`/v1/customers/${id}`);
  return response.data.data;
};

const fetchCustomerByBAN = async (ban: string): Promise<Customer> => {
  const response = await api.get<APIResponse<Customer>>(`/v1/customers/by-ban/${ban}`);
  return response.data.data;
};

const createCustomer = async (data: CreateCustomerRequest): Promise<Customer> => {
  const response = await api.post<APIResponse<Customer>>('/v1/customers', data);
  return response.data.data;
};

const updateCustomer = async ({
  id,
  data,
}: {
  id: string;
  data: UpdateCustomerRequest;
}): Promise<Customer> => {
  const response = await api.put<APIResponse<Customer>>(`/v1/customers/${id}`, data);
  return response.data.data;
};

const fetchCustomerTrunks = async (id: string): Promise<any[]> => {
  const response = await api.get<APIResponse<any[]>>(`/v1/customers/${id}/trunks`);
  return response.data.data;
};

const fetchCustomerDIDs = async (id: string): Promise<any[]> => {
  const response = await api.get<APIResponse<any[]>>(`/v1/customers/${id}/dids`);
  return response.data.data;
};

// React Query Hooks

/**
 * Hook to fetch paginated list of customers
 */
export const useCustomers = (
  page = 1,
  perPage = 20,
  search?: string,
  status?: string,
  options?: Omit<UseQueryOptions<CustomerListResponse>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<CustomerListResponse>({
    queryKey: ['customers', page, perPage, search, status],
    queryFn: () => fetchCustomers(page, perPage, search, status),
    staleTime: 30000, // 30 seconds
    ...options,
  });
};

/**
 * Hook to fetch a single customer by ID
 */
export const useCustomer = (
  id: string,
  options?: Omit<UseQueryOptions<Customer>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<Customer>({
    queryKey: ['customer', id],
    queryFn: () => fetchCustomer(id),
    enabled: !!id,
    ...options,
  });
};

/**
 * Hook to fetch a customer by BAN
 */
export const useCustomerByBAN = (
  ban: string,
  options?: Omit<UseQueryOptions<Customer>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<Customer>({
    queryKey: ['customer', 'ban', ban],
    queryFn: () => fetchCustomerByBAN(ban),
    enabled: !!ban,
    ...options,
  });
};

/**
 * Hook to create a new customer
 */
export const useCreateCustomer = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: createCustomer,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['customers'] });
    },
  });
};

/**
 * Hook to update an existing customer
 */
export const useUpdateCustomer = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: updateCustomer,
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['customers'] });
      queryClient.invalidateQueries({ queryKey: ['customer', data.id] });
    },
  });
};

/**
 * Hook to fetch customer trunks
 */
export const useCustomerTrunks = (
  customerId: string,
  options?: Omit<UseQueryOptions<any[]>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<any[]>({
    queryKey: ['customer', customerId, 'trunks'],
    queryFn: () => fetchCustomerTrunks(customerId),
    enabled: !!customerId,
    ...options,
  });
};

/**
 * Hook to fetch customer DIDs
 */
export const useCustomerDIDs = (
  customerId: string,
  options?: Omit<UseQueryOptions<any[]>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<any[]>({
    queryKey: ['customer', customerId, 'dids'],
    queryFn: () => fetchCustomerDIDs(customerId),
    enabled: !!customerId,
    ...options,
  });
};
