language: node_js
node_js:
- '6'
notifications:
  email:
    on_success: never
    on_failure: never
jobs:
  include:
    - stage: "Tests"
      name: Lint Test
      script: npm run lint
    - script: npm run build
      name: Build Test
