apiVersion: v1
kind: Pod
metadata:
  name: test-db-connection
  namespace: warp-core
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    command: ['sh', '-c', 'while true; do sleep 30; done;']
    env:
    - name: PGHOST
      value: "10.126.0.3"
    - name: PGPORT
      value: "5432"
    - name: PGDATABASE
      value: "warp"
    - name: PGUSER
      value: "warp"
    - name: PGPASSWORD
      value: ")T]!sXUi>SE+DeWt6a8Wmy*Q)A4q6R:}"